### ISSUE TITLE
[GCE] Ajout du compteur journalier

### ISSUE THREAD

**Issue by lboue** [rene-d/gce#1]
Bonjour,

Pourriez-vous ajouter le support du compteur journalier. Voici un exemple de requête à l'API :  

```
pi@raspberrypi:~ $ curl -s http://192.168.1.7/api/xdevices.json?cmd=20 |jq
{
  "product": "Eco-devices",
  "Day_C1": 428,
  "Day_C2": 0
}
```

Merci

**Comment by rene-d** [comment]
Bonsoir,

J'ai rajouté des fonctions pour envoyer la requête (ainsi que status.xml et l'autre json). Cependant je ne sais pas si ça remplira ton besoin...

Merci pour ton intérêt :)

**Comment by lboue** [comment]
Bonsoir,

C'est parfait  👍
